services:
  - type: web
    name: crop-yield-prediction
    runtime: python
    plan: free
    # Since everything is at the root
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
